-- CreateTable
CREATE TABLE "ParentPage" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "url" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "maxPage" INT4 NOT NULL,

    CONSTRAINT "ParentPage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Page" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "pageNumber" INT4 NOT NULL,
    "parentId" INT4 NOT NULL,

    CONSTRAINT "Page_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Image" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "url" STRING NOT NULL,
    "pageId" INT4 NOT NULL,

    CONSTRAINT "Image_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ParentPage_url_key" ON "ParentPage"("url");

-- CreateIndex
CREATE UNIQUE INDEX "Page_parentId_pageNumber_key" ON "Page"("parentId", "pageNumber");

-- AddForeignKey
ALTER TABLE "Page" ADD CONSTRAINT "Page_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "ParentPage"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Image" ADD CONSTRAINT "Image_pageId_fkey" FOREIGN KEY ("pageId") REFERENCES "Page"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
